# Generated by Django 5.2.6 on 2025-09-13 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название тега")),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Цвет тега"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название задачи"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание задачи"),
                ),
                ("due_date", models.DateTimeField(verbose_name="Дата выполнения")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Выполнена"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.project",
                        verbose_name="Проект",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="api.tag", verbose_name="Теги"
                    ),
                ),
            ],
        ),
    ]
