# Generated by Django 5.2.6 on 2025-12-27 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_tag_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_at", models.DateTimeField(verbose_name="Дата отправки")),
                (
                    "is_sent",
                    models.BooleanField(default=False, verbose_name="Статус отправки"),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("email", "Электронная почта"),
                            ("telegram", "Телеграм"),
                        ],
                        max_length=30,
                        verbose_name="Способ получения уведомления",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="api.task",
                        verbose_name="Задача",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecurringTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("daily", "Ежедневно"),
                            ("weekly", "Еженедельно"),
                            ("monthly", "Ежемесячно"),
                            ("yerly", "Ежегодно"),
                        ],
                        max_length=20,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(verbose_name="Дата начала повторений"),
                ),
                (
                    "end_date",
                    models.DateTimeField(verbose_name="Дата окончания повторений"),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.task",
                        verbose_name="Задача",
                    ),
                ),
            ],
        ),
    ]
